- .gitignore
- src/dev/ContentList.tsx
- src/lib/config/index.tsx
- src/modules/ContentList/index.tsx
- src/modules/ContentList/test.tsx
> Content widget

- src/modules/Content/index.tsx
- src/modules/Content/test.tsx
> Fix content search

- src/components/Svg/Plus.tsx
- src/dev/RecordingList.tsx
- src/lib/config/index.tsx
- src/modules/RecordingList/index.tsx
- src/modules/RecordingList/test.tsx
> Custom calls

- src/modules/EventList/index.tsx
- src/modules/EventList/test.tsx
- src/modules/RecordingList/index.tsx
> Switch to new search endpoint and add search hit count to event results

- src/modules/ContentList/index.tsx
- src/modules/ContentList/test.tsx
Replaces `content` query in `ContentList` module with `search` query and results
> Content gql

- src/dev/NewsList.tsx
- src/lib/config/index.tsx
- src/lib/data/index.ts
- src/lib/datetimes/index.ts
- src/lib/datetimes/test.ts
- src/modules/ContentList/styles.css
- src/modules/News/index.tsx
- src/modules/News/test.tsx
- src/modules/NewsList/index.tsx
- src/modules/NewsList/test.tsx
> Content to news

- src/modules/RecordingForm/index.tsx
- src/modules/RecordingForm/test.tsx
- src/modules/RecordingList/index.tsx
- src/modules/RecordingList/test.tsx
> Recording form

- src/modules/News/index.tsx
- src/modules/News/test.tsx
- src/modules/NewsList/index.tsx
- src/modules/NewsList/test.tsx
> Clear news

- src/modules/Transcript/PriceChart/index.tsx
- src/web/demo/EventList.html
Same as other branch but with signed commits
> changing text color and showing settings

- src/api/auth.ts
- src/api/client.tsx
- src/components/Playbar/index.tsx
- src/lib/config/index.tsx
- src/lib/msg/index.tsx
- src/modules/Auth/index.tsx
- src/modules/Auth/test.tsx
- src/modules/Transcript/Header/index.tsx
- src/modules/Transcript/Header/test.tsx
- src/modules/Transcript/index.tsx
- src/modules/Transcript/test.tsx
- src/web/demo/ASRTranscript.html
- src/web/embed.ts
- src/web/modules/ASRTranscript/index.html
- src/web/modules/ASRTranscript/index.tsx
https://trello.com/c/LgD07oIL/1349-asr-widget
https://trello.com/c/9KkoORLq/1373-add-public-api-keys-to-users-and-update-aiera-public-api-to-validate-requests-with-public-api-keys-against-the-whitelisted-domai
> ASR Widget

- src/components/Playbar/index.tsx
- src/lib/config/index.tsx
- src/modules/Transcript/Header/index.tsx
- src/modules/Transcript/Header/test.tsx
- src/modules/Transcript/index.tsx
- src/web/demo/EventByTicker.html
- src/web/modules/EventByTicker/index.html
- src/web/modules/EventByTicker/index.tsx
[# Trello card link
](https://trello.com/c/ecAsd4eP/1415-single-event-widget-asr-widget-put-in-ticker-return-latest-earnings-call)
> Support Event by Ticker

- src/modules/Auth/index.tsx
> pass up js origin with api auth

- package.json
- src/lib/config/index.tsx
- src/lib/msg/index.tsx
- src/modules/EventList/index.tsx
- src/modules/Transcript/Header/index.tsx
- src/modules/Transcript/index.tsx
- src/web/demo/ASRTranscript.html
- src/web/demo/EventByTicker.html
- src/web/demo/EventListByTicker.html
- src/web/embed.ts
- src/web/modules/EventListByTicker/index.html
- src/web/modules/EventListByTicker/index.tsx
> Eventlist ticker

- src/api/client.tsx
- src/lib/config/index.tsx
- src/lib/data/index.ts
- src/lib/msg/index.tsx
- src/modules/EventList/index.tsx
- src/web/demo/EventByTicker.html
- src/web/demo/EventListByTicker.html
- [x ] I have performed a self-review of my code
> feat: Auth by user status in config

- src/lib/data/index.ts
- src/modules/EventList/index.tsx
> Feat: Track user status check

- .gitignore
- src/components/Checkbox/index.tsx
- src/components/Checkbox/test.tsx
- src/components/Textarea/index.tsx
- src/components/Textarea/test.tsx
- src/modules/RecordingForm/ConnectionDetails/index.tsx
- src/modules/RecordingForm/ConnectionDetails/test.tsx
- src/modules/RecordingForm/Troubleshooting/index.tsx
- src/modules/RecordingForm/Troubleshooting/test.tsx
- src/modules/RecordingForm/index.tsx
- src/modules/RecordingForm/types.ts
https://trello.com/c/WE739HYL/1196-troubleshooting-sub-module-ui
> Troubleshooting

- src/components/CompanyFilterButton/index.tsx
- src/components/CompanyFilterButton/test.tsx
- src/components/CompanySelect/index.tsx
- src/components/CompanySelect/test.tsx
- src/modules/RecordingForm/RecordingDetails/index.tsx
- src/modules/RecordingForm/RecordingDetails/styles.css
- src/modules/RecordingForm/RecordingDetails/test.tsx
- src/modules/RecordingForm/index.tsx
https://trello.com/c/yEZ6jMSj/1197-recordingdetails-sub-module-ui
> Recording details

- package.json
- src/lib/audio/index.tsx
> Bug Fix: Trigger update on seek when not playing

- src/lib/msg/index.tsx
- src/modules/EventList/index.tsx
- src/web/demo/EventList.html
Broadcast a message when an event is selected
> Event selected

- src/lib/config/index.tsx
- src/modules/Transcript/index.tsx
> Config flag for relative timestamps

- src/lib/config/index.tsx
- src/lib/hooks/useAutoScroll/index.ts
- src/modules/Transcript/index.tsx
> bug: Autoscroll fix

- package.json
- src/components/CompanyFilterButton/index.tsx
- src/components/Playbar/index.tsx
- src/components/SettingsButton/index.tsx
- src/lib/config/index.tsx
- src/modules/Auth/index.tsx
- src/modules/EventList/FilterBy/index.tsx
- src/modules/EventList/PlayButton/index.tsx
- src/modules/EventList/index.tsx
- src/modules/Transcript/EventDetails/index.tsx
- src/modules/Transcript/Header/index.tsx
- src/modules/Transcript/PriceChart/index.tsx
- src/modules/Transcript/index.tsx
- src/web/demo/EventList.html
- src/web/demo/EventListByTicker.html
- src/web/demo/RecordingList.html
- src/web/modules/EventList/index.tsx
- src/web/modules/EventListByTicker/index.tsx
- src/web/modules/RecordingList/index.tsx
> Style override

- src/modules/Aieracast/index.tsx
> feat: define type arg for toggle event in aieracast

- src/web/demo/Aieracast.html
> chore: clean up aieracast demo

- package.json
- src/modules/Transcript/index.tsx
> fix: prevent seeking on events unrelated to current event

- package-lock.json
- src/modules/Aieracast/test.tsx
https://trello.com/c/7xsQqo4G/1675-fix-add-aieracast-component-tests
> chore: fix and add Aieracast tests and include package-lock updates from prior release

- package.json
- src/lib/msg/index.tsx
- src/web/embed.ts
> fix: update types for message bus listener argument

- package.json
- src/lib/config/index.tsx
- src/lib/data/index.ts
- src/modules/Aieracast/index.tsx
- src/modules/EventList/index.tsx
- src/modules/Transcript/index.tsx
- src/web/demo/EventList.html
> Track widget user

- package-lock.json
- package.json
- src/lib/config/index.tsx
- src/modules/Transcript/index.tsx
- src/web/demo/EventList.html
> support for hiding sentiment and partials

- src/lib/config/index.tsx
- src/modules/Transcript/index.tsx
- src/web/demo/EventList.html
> chore: rename hidePartials hideSentiment to showPartials showSentiment

- src/components/Playbar/index.tsx
- src/lib/audio/index.tsx
- src/modules/Transcript/index.tsx
- src/types/shaka.ts
> disable autoplay - do not use trickPlay - use setPlaybackrate instead

- .jest/jest-setup.js
- README.md
- package-lock.json
> chore: silence console log statements in tests, update README for editing console statements in tests, and upgrade caniuse-lite

- package-lock.json
- package.json
- src/lib/msg/index.tsx
- src/web/demo/EventListMulti.html
- src/web/embed.ts
> feat: only send messages for the proper iframe modules

- src/lib/msg/index.tsx
- src/web/embed.ts
> feat: use url params for frameId

- src/components/Playbar/index.tsx
- src/types/shaka.ts
> add type function + make sure to unload player when unmount happens

- src/lib/data/index.ts
- src/modules/EventList/index.tsx
- src/modules/NewsList/index.tsx
Depends on https://github.com/aiera-inc/aiera-public-api/pull/44
https://trello.com/c/OnGR0q5p/1734-refactor-ticker-resolution-for-watchlist-setting-in-components
> Resolution identifiers

- package-lock.json
- package.json
- src/lib/config/index.tsx
- src/lib/data/index.ts
- src/lib/data/test.tsx
- src/lib/msg/index.tsx
- src/modules/EventList/index.tsx
- src/modules/EventList/test.tsx
- src/web/demo/Aieracast.html
- src/web/demo/EventList.html
- src/web/demo/EventListMulti.html
https://trello.com/c/PoGt8t91/1740-dynamically-create-users-and-primary-watchlists-from-component-companyresolution-queries-and-use-watchlistid-instead-of-companyi
> Set watchlist user

- src/lib/config/index.tsx
- src/modules/Transcript/Header/index.tsx
- src/modules/Transcript/index.tsx
- src/modules/Transcript/styles.css
- src/web/demo/EventByTicker.html
> feat: print transcript

- src/lib/msg/index.tsx
- src/modules/Transcript/Header/index.tsx
- src/modules/Transcript/styles.css
- src/web/embed.ts
> Print frame

- src/modules/Transcript/Header/index.tsx
- src/modules/Transcript/styles.css
- src/web/embed.ts
> test: print msg

- src/modules/Transcript/styles.css
> test: hide css

- src/modules/EventList/index.tsx
https://trello.com/c/40TqP3g7/1746-handle-empty-null-watchlists-and-refetch-when-it-changes-in-components
> fix(EventList): fire upsertPrimaryWatchlist mutation even with empty list and refetch both queries when watchlist changes

- src/lib/audio/index.tsx
- src/modules/Transcript/index.tsx
- src/web/demo/ASRTranscript.html
- src/web/demo/EventList.html
> testing: offset seek bug

- src/modules/EventList/index.tsx
> feat: loading watchlist UI

- src/web/modules/ASRTranscript/index.tsx
- src/web/modules/EventByTicker/index.tsx
> update: hide header controls by default

- src/lib/data/index.ts
- src/lib/data/test.tsx
- src/modules/EventList/index.tsx
- src/web/embed.ts
https://trello.com/c/EsWTpMYp/1748-support-fdc3-identifiers-in-upsertprimarywatchlist-mutation-for-fido
> refactor: support FDC3-formatted list of identifiers in upsertPrimaryWatchlist

- package-lock.json
- package.json
- src/components/Svg/Handle.tsx
- src/components/Toggle/index.tsx
- src/modules/Aieracast/index.tsx
- src/modules/Aieracast/styles.css
- src/modules/Transcript/Header/index.tsx
- src/modules/Transcript/index.tsx
- src/modules/Transcript/styles.css
- src/web/demo/Aieracast.html
- src/web/demo/EventList.html
> Aieracast dnd

- src/components/Playbar/index.tsx
> patch: zindex for playbar

- package-lock.json
- package.json
- src/lib/audio/index.tsx
- src/modules/EventList/index.tsx
- src/modules/Transcript/index.tsx
> fix: add missing dependency for latest paragraphs

- src/modules/Aieracast/index.tsx
- src/modules/EventList/index.tsx
- src/web/demo/EventList.html
- src/web/demo/RecordingList.html
> update: no earnings release for aieracast

- src/components/SettingsButton/index.tsx
- src/components/Toggle/index.tsx
> fix: quiet toggle warning on unmount

- package-lock.json
- package.json
- src/modules/Auth/index.tsx
> Call loginWithApiKey again if the login state is error and the parent origin changes

- package-lock.json
- package.json
- src/modules/Auth/index.tsx
> fix: reduce to single auth request

- package-lock.json
- package.json
- src/lib/config/index.tsx
- src/modules/Transcript/index.tsx
> Support triming a transcript by seconds

- package-lock.json
- package.json
- src/modules/Auth/index.tsx
> Fix: logout prev sessions before logging in

- package-lock.json
- package.json
- src/lib/config/index.tsx
- src/modules/Transcript/index.tsx
> feat: support for trimming a transcript by the raw seconds

- package-lock.json
- package.json
- src/lib/audio/index.tsx
- src/modules/Aieracast/index.tsx
- src/modules/EventList/index.tsx
- src/modules/EventList/test.tsx
- src/modules/Transcript/Header/index.tsx
- src/modules/Transcript/index.tsx
- src/types/index.ts
- src/types/mux.d.ts
- src/web/demo/EventList.html
- src/web/modules/EventList/index.html
https://trello.com/c/GGtoLkgN/1855-support-externalaudiostreamurls-in-components-used-by-private-recording-clients-that-provide-their-own-live-streams-eg-oe
> feat: use liveStreamUrl instead of hardcoded url for live events and use externalAudioStreamUrl instead of media-proxy redirect url when set

- src/lib/audio/index.tsx
- src/types/shaka.ts
> fix the seek issue for live and recent events

- src/modules/Aieracast/index.tsx
- src/modules/EventList/index.tsx
> design: Align ticker and exchange on baseline in event row

- package-lock.json
- package.json
- src/modules/Transcript/index.tsx
> bugfix: no speakers when latest paragraphs

- src/modules/Transcript/index.tsx
> enhancement: refetching mode for lastestParagraphs

- package-lock.json
- package.json
- src/lib/audio/index.tsx
> Playsinline

- src/modules/Auth/index.tsx
- src/modules/Transcript/EventDetails/index.tsx
> add ability to download transcript - pdf

- src/modules/Transcript/EventDetails/index.tsx
> hide pdf download for live event

- package-lock.json
- package.json
- src/modules/Transcript/EventDetails/index.tsx
> Download pdf

- package-lock.json
- package.json
- src/lib/hooks/useAutoScroll/index.ts
- src/modules/Transcript/index.tsx
> Feature: Force scroll when clicking seeking by date

- package-lock.json
- package.json
- src/components/Button/index.tsx
- src/components/Svg/Download.tsx
- src/components/Tooltip/index.tsx
- src/lib/config/index.tsx
- src/modules/EventList/test.tsx
- src/modules/Transcript/DownloadTooltip/index.tsx
- src/modules/Transcript/DownloadTooltip/test.tsx
- src/modules/Transcript/EventDetails/index.tsx
- src/modules/Transcript/EventDetails/test.tsx
- src/modules/Transcript/Header/index.tsx
- src/modules/Transcript/Header/test.tsx
- src/modules/Transcript/index.tsx
- src/modules/Transcript/test.tsx
> Download tooltip

- package-lock.json
- package.json
- src/modules/Transcript/DownloadTooltip/index.tsx
> Fix: dont propagate click events in download tooltip

- src/modules/Transcript/DownloadTooltip/index.tsx
> update: hide tooltip on download

- package-lock.json
- package.json
- src/components/PlayButton/index.tsx
- src/components/Playbar/index.tsx
- src/lib/audio/index.tsx
- src/lib/data/index.ts
> Duration log

- src/api/client.tsx
- src/lib/realtime/index.tsx
https://trello.com/c/IV9drnI7/2136-stop-realtimecurrentuser-query-in-client-sdk-from-hammering-public-api-when-theres-an-error
> chore: check if user is authed every 5 seconds in realtime provider

- src/modules/Transcript/index.tsx
- src/web/demo/ASRTranscript.html
> fix: darkmode styles for summary

- src/api/client.tsx
- src/lib/realtime/index.tsx
- src/modules/Transcrippet/index.tsx
- src/modules/Transcrippet/test.tsx
- src/web/demo/Transcrippet.html
> Component header

- src/modules/Transcrippet/index.tsx
> feature: transcrippet select word seek audio

- src/modules/Transcrippet/index.tsx
> feature: link transcrippet to aiera

- src/modules/Transcrippet/index.tsx
> fix: handle no audio for transcrippets

- src/modules/Auth/index.tsx
> fix: login again when expired token

- src/modules/Transcrippet/LineChart.tsx
- src/modules/Transcrippet/index.tsx
- src/web/demo/Transcrippet.html
> Support Price Chart with Transcrippet

- src/components/PlayButton/index.tsx
- src/components/Playbar/index.tsx
> update: include eventId in event-audio message

- package-lock.json
- package.json
- src/components/PlayButton/index.tsx
- src/components/Playbar/index.tsx
- src/lib/audio/index.tsx
- src/modules/EventList/index.tsx
- src/modules/Transcrippet/index.tsx
- src/modules/Transcript/Header/index.tsx
- src/modules/Transcript/index.tsx
> Event audio bug

- package-lock.json
- package.json
- src/lib/msg/index.tsx
- src/modules/Transcript/EventDetails/index.tsx
- src/modules/Transcript/EventDetails/test.tsx
- src/modules/Transcript/Header/index.tsx
- src/modules/Transcript/Header/test.tsx
- src/modules/Transcript/ReportIssue/index.tsx
- src/modules/Transcript/ReportIssue/test.tsx
- src/modules/Transcript/index.tsx
> Report issue

- package-lock.json
- package.json
- src/lib/audio/index.tsx
> Dynamically set amp url based on NODE_ENV

- package-lock.json
- package.json
- src/modules/Transcript/index.tsx
> Pause scroll search

- src/lib/realtime/index.tsx
Kanban Card Link: { CARD_LINK}
```text
PR Guidelines
1. Aim to create small, focused pull requests that fulfill a single purpose.
Smaller pull requests are easier and faster to review and merge, leave less room to introduce bugs, and
provide a clearer history of changes.
2. Review, build, and test your own pull request before submitting it.
This will allow you to catch errors or typos that you may have missed, before others start reviewing.
3. Write clear titles and descriptions for your pull requests so that reviewers can quickly understand what
the pull request does.
--> If your pull request consists of changes to multiple files, provide guidance to reviewers about the
order in which to review the files. Recommend where to start and how to proceed with the review.
```
_Links to any …
> patch: stableCallback

- package.json
- src/lib/config/index.tsx
- src/modules/EventList/index.tsx
- src/web/demo/EventList.html
Kanban Card Link: { CARD_LINK}
```text
PR Guidelines
1. Aim to create small, focused pull requests that fulfill a single purpose.
Smaller pull requests are easier and faster to review and merge, leave less room to introduce bugs, and
provide a clearer history of changes.
2. Review, build, and test your own pull request before submitting it.
This will allow you to catch errors or typos that you may have missed, before others start reviewing.
3. Write clear titles and descriptions for your pull requests so that reviewers can quickly understand what
the pull request does.
--> If your pull request consists of changes to multiple files, provide guidance to reviewers about the
order in which to review the files. Recommend where to start and how to proceed with the review.
```
_Links to any …
> Feature: showCompanyNameInEventRow flag

- package.json
- src/modules/EventList/index.tsx
Kanban Card Link: { CARD_LINK}
```text
PR Guidelines
1. Aim to create small, focused pull requests that fulfill a single purpose.
Smaller pull requests are easier and faster to review and merge, leave less room to introduce bugs, and
provide a clearer history of changes.
2. Review, build, and test your own pull request before submitting it.
This will allow you to catch errors or typos that you may have missed, before others start reviewing.
3. Write clear titles and descriptions for your pull requests so that reviewers can quickly understand what
the pull request does.
--> If your pull request consists of changes to multiple files, provide guidance to reviewers about the
order in which to review the files. Recommend where to start and how to proceed with the review.
```
_Links to any …
> feature: override watchlist with filtered company

- package-lock.json
- src/components/Provider/test.tsx
- src/modules/AieraChat/components/Header/Search/index.tsx
- src/modules/AieraChat/components/Header/index.tsx
- src/modules/AieraChat/components/Messages/index.tsx
- src/modules/AieraChat/index.tsx
- src/modules/AieraChat/modals/ConfirmDialog/index.tsx
- src/modules/AieraChat/panels/Menu/index.tsx
- src/modules/AieraChat/services/chats.ts
- src/modules/Transcript/DownloadTooltip/index.tsx
Kanban Card Link: { CARD_LINK}
```text
PR Guidelines
1. Aim to create small, focused pull requests that fulfill a single purpose.
Smaller pull requests are easier and faster to review and merge, leave less room to introduce bugs, and
provide a clearer history of changes.
2. Review, build, and test your own pull request before submitting it.
This will allow you to catch errors or typos that you may have missed, before others start reviewing.
3. Write clear titles and descriptions for your pull requests so that reviewers can quickly understand what
the pull request does.
--> If your pull request consists of changes to multiple files, provide guidance to reviewers about the
order in which to review the files. Recommend where to start and how to proceed with the review.
```
_Links to any …
> Chat sessions

- src/modules/AieraChat/index.tsx
- src/modules/AieraChat/modals/AddSourceDialog/index.tsx
- src/modules/AieraChat/panels/Menu/index.tsx
- src/modules/AieraChat/panels/Sources/index.tsx
- src/modules/AieraChat/services/chats.ts
- src/modules/AieraChat/store.ts
> Chat session sources

- src/modules/AieraChat/components/Messages/MessageFactory/Block/Chart/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/Block/Table/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/Block/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/MessageResponse/Footer/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/SourcesResponse/index.tsx
- src/modules/AieraChat/components/Messages/index.tsx
- src/modules/AieraChat/services/chats.ts
- src/modules/AieraChat/services/messages.ts
> Chat messages

- src/lib/utils/index.ts
- src/modules/AieraChat/components/Messages/MessageFactory/Block/Chart/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/Block/Table/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/Block/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/MessageResponse/Footer/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/MessageResponse/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/SourcesResponse/index.tsx
- src/modules/AieraChat/components/Messages/index.tsx
- src/modules/AieraChat/index.tsx
- src/modules/AieraChat/services/chats.ts
- src/modules/AieraChat/services/messages.ts
> Create message prompts

- src/modules/AieraChat/components/Messages/index.tsx
> Disable bot message response streaming

- src/modules/AieraChat/components/Messages/MessageFactory/Block/Table/index.tsx
- src/modules/AieraChat/components/Messages/index.tsx
- src/modules/AieraChat/services/graphql.ts
- src/modules/AieraChat/services/messages.ts
> Fix chat polling

- src/api/client.tsx
- src/modules/AieraChat/services/messages.ts
- src/modules/AieraChat/store.ts
> Session titles

- src/modules/AieraChat/panels/Panel/index.tsx
- src/modules/AieraChat/panels/Panel/styles.css
> fix: animate forwards class

- src/modules/AieraChat/panels/Panel/index.tsx
> fix: panel bg animate

- src/modules/AieraChat/components/AnimatedLoadingStatus/index.tsx
- src/modules/AieraChat/components/Messages/index.tsx
- src/modules/AieraChat/index.tsx
- src/modules/AieraChat/panels/Menu/index.tsx
- src/modules/AieraChat/services/chats.ts
- src/modules/AieraChat/services/graphql.ts
- src/modules/AieraChat/services/messages.ts
- src/modules/AieraChat/store.ts
> Session status

- src/modules/AieraChat/index.tsx
> enhancement: chat transcript to respect config options

- src/components/PlayButton/index.tsx
- src/components/Playbar/index.tsx
- src/lib/hooks/useDrag/index.ts
> enhancement: support mobile touch events for dragging the audio scrubber

- src/api/client.tsx
- src/modules/AieraChat/services/chats.ts
- src/modules/AieraChat/services/messages.ts
- src/web/demo/AieraChatInternal.html
> Chat unique users

- src/web/demo/AieraChat.html
- src/web/demo/AieraChatInternal.html
> enhancement: update chat demo width to 800px

- src/components/Svg/MicroChatLeftRight.tsx
- src/components/Svg/MicroDocumentSearch.tsx
- src/lib/config/index.tsx
- src/modules/AieraChat/components/ContentRow/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/MessageResponse/Footer/index.tsx
- src/modules/AieraChat/modals/FeedbackDialog/index.tsx
- src/modules/AieraChat/modals/Modal/index.tsx
- src/modules/AieraChat/panels/Sources/index.tsx
- src/web/demo/AieraChatInternal.html
> Feedback form

- src/modules/AieraChat/components/Messages/MessageFactory/SourcesResponse/index.tsx
- src/modules/AieraChat/components/Messages/Prompt/index.tsx
- src/modules/AieraChat/components/Messages/index.tsx
- src/modules/AieraChat/services/ably.ts
- src/modules/AieraChat/services/chats.ts
- src/modules/AieraChat/services/graphql.ts
- src/modules/AieraChat/services/messages.ts
> Confirm sources

- src/modules/AieraChat/components/IconButton/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/MessageResponse/Footer/index.tsx
- src/modules/AieraChat/modals/FeedbackDialog/index.tsx
> feature: confirm closing feedback with unsaved changes

- src/modules/AieraChat/components/Messages/MessageFactory/index.tsx
- src/modules/AieraChat/components/Messages/Prompt/index.tsx
- src/modules/AieraChat/components/Messages/Prompt/styles.css
- src/modules/AieraChat/components/Messages/index.tsx
- src/modules/AieraChat/panels/Panel/index.tsx
> feature: max width for chat messages and panels

- src/modules/AieraChat/components/ContentRow/index.tsx
- src/modules/AieraChat/components/Header/index.tsx
- src/modules/AieraChat/panels/Sources/index.tsx
- src/modules/AieraChat/store.ts
> Chat enhancements

- src/modules/AieraChat/modals/AddSourceDialog/index.tsx
> enhancement: add dates to source edit modal in AieraChat

- src/modules/AieraChat/components/Messages/MessageFactory/Block/Text/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/Block/Text/markdown.tsx
- src/modules/AieraChat/components/Messages/index.tsx
- src/modules/AieraChat/services/messages.ts
- src/modules/AieraChat/store.ts
> Extend Text block to support markdown style

- src/modules/AieraChat/components/Messages/MessageFactory/Block/Text/markdown.tsx
- src/modules/AieraChat/services/ably.ts
> Chat fixes

- src/modules/AieraChat/services/ably.ts
> Only process response partials when non-final

- .claude/settings.local.json
- src/api/client.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/Block/Text/markdown.css
- src/modules/AieraChat/components/Messages/MessageFactory/Citation/index.tsx
- src/modules/AieraChat/components/Messages/index.tsx
- src/modules/AieraChat/services/ably.ts
> Ably history

- src/modules/AieraChat/services/ably.ts
> Don't stop streaming when status messages are consumed

- src/modules/AieraChat/components/Messages/index.tsx
- src/modules/AieraChat/store.ts
> Fix bug with clearing streamed responses when closing sources panel

- .claude/settings.local.json
- src/modules/AieraChat/components/Messages/MessageFactory/Block/Text/markdown.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/Block/Text/test.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/Block/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/Citation/index.tsx
- src/modules/AieraChat/services/ably.ts
- src/modules/AieraChat/services/messages.ts
- src/modules/AieraChat/store.ts
> Chat citations

- src/modules/AieraChat/components/Messages/MessageFactory/Block/Text/markdown.tsx
- src/modules/AieraChat/store.ts
> New citation markers

- .claude/settings.local.json
- src/api/client.tsx
- src/modules/AieraChat/services/ably.ts
- src/modules/AieraChat/services/chats.ts
- src/modules/AieraChat/store.ts
> Fix auto confirming

- .claude/settings.local.json
- src/modules/AieraChat/components/Messages/MessageFactory/Citation/test.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/test.tsx
- src/modules/AieraChat/components/Messages/test.tsx
- src/modules/AieraChat/store.test.ts
- src/modules/AieraChat/test.tsx
> Fix linting issues in tests

- src/modules/AieraChat/services/ably.ts
> patch: fix utf chat decoding

- src/modules/AieraChat/components/Messages/MessageFactory/MessageResponse/Footer/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/MessageResponse/index.tsx
- src/web/demo/EventList.html
> Message sources

- src/modules/AieraChat/components/Hint/index.tsx
- src/modules/AieraChat/components/Messages/MessageFactory/Citation/index.tsx
- src/modules/AieraChat/components/Messages/index.tsx
> enhancement: hint for citations

- src/modules/AieraChat/components/Messages/index.tsx
- src/modules/AieraChat/components/Messages/test.tsx
- src/modules/AieraChat/services/ably.ts
> Set default thinking state to 'Finding sources...' and update tests
